### ISSUE TITLE
Using on windows

### ISSUE THREAD

**Issue by hookedgeardev** [enderandpeter/wpgithooks#3]
For anyone who wants to use this on windows, I have the following in C:\bin :

+ wp.bat (for command line)

`@ECHO OFF
SET BIN_TARGET=%~dp0/./wp-cli.phar
php "%BIN_TARGET%" %*`

+ wp (for git bash)

`#!/usr/bin/env sh
dir=$(d=${0%[/\\]*}; cd "$d"; pwd)
if command -v 'cygpath' >/dev/null 2>&1; then
   if [[ $(which php) == /cygdrive/* ]]; then
       dir=$(cygpath -m $dir);
   fi
fi
dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/wp-cli.phar" "$@"`

+ wp-cli.phar (https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar)

run `chmod +x wp-cli.phar`

Add C:\bin\ to your PATH environment variables
Add a directory containing your local php.exe to your PATH environment variables

Now you can run (./setup.sh using git bash) or (setup using cmd)

**Comment by enderandpeter** [comment]
Thank you very much for sharing this info. It does look useful. That is quite an involved shell script command. Still trying to wrap my head around it.

I only tried the regular wp-cli.phar directly in Git Bash for Windows a few years ago and it worked well from what I remember, but I'm curious to compare your method. I have gotten used to setting up WordPress sites in Docker containers, so I typically end up in a Linux environment.

I'm going to close this issue only because it is really intriguing advice rather than an issue, but I want to make sure this comment is still publicly accessible for now until I may decide to establish a discussion area somewhere for this tool. I'm really glad you have found these scripts of use. I will dive back into this project really soon.
